### ISSUE TITLE
Prepare README.md

### ISSUE THREAD

**Issue by mxmar** [lukso-network/l16-deploy-node-gcloud#6]
As a developer I would like to able to have full filled README which covering all steps to execute script properly.

**Comment by mxmar** [comment]
First version (`v.1.0`) of `README.md` is provided in https://github.com/lukso-network/l16-deploy-node-gcloud/tree/readme

**Comment by patred20** [comment]
Merged in https://github.com/lukso-network/l16-deploy-node-gcloud/pull/9
